org.gradle.jvmargs=-Xmx4G -XX:+UseG1GC -XX:MaxMetaspaceSize=1024m -XX:ReservedCodeCacheSize=256m
org.gradle.java.home=C\:\\Program Files\\Eclipse Adoptium\\jdk-17.0.20.101-hotspot
org.gradle.workers.max=2
org.gradle.parallel=false
android.useAndroidX=true
android.enableR8.fullMode=false
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
